sync_address = "https://shell.tibl.dev"
auto_sync = true

enter_accept = true
workspaces = true
show_help = false

prefers_reduced_motion = true

[sync]
records = true

[stats]
common_prefix = ["sudo"]
