theme = "nord"

[editor]
bufferline = "multiple"
cursorline = false
line-number = "relative"
rulers = []

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 1

[keys.normal]
# Buffer navigation using Alt+,.
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
# Replace X with selecting a line above
"X" = "extend_line_above"
