[user]
name = "Til Blechschmidt"
email = "me@tibl.dev"

[signing]
sign-all = true
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII/RQS4p5LRMtn8JgU0mvbMNmFfQlXIC48Qv8L03sB4A"

[ui]
default-command = "log"
paginate = "auto"
pager = "delta"
diff-editor = ":builtin"

[ui.diff]
format = "git"

[aliases]
l = ["log", "-r", "@ | ancestors(immutable_heads().., 2) | trunk()"]

[template-aliases]
'format_short_signature(signature)' = 'signature.username()'
'format_timestamp(timestamp)' = 'timestamp.format("%F %H:%M")'

[revsets]
log = 'log_set'

[revset-aliases]
'my_remote_heads' = 'heads(mine() & remote_branches()) ~ ::trunk()'
'my_heads' = 'heads(mine()) ~ empty() ~ ::remote_only_branches ~ ::trunk()'

'remote_only_branches' = 'remote_branches() ~ branches() ~ my_remote_heads'
'trunk_parents' = '::(trunk()-)'

'working_set' = '((branches() ~ trunk()) | my_heads | my_remote_heads):: | @'
'log_set' = 'reachable(working_set, ~trunk_parents) ~ trunk()+::remote_only_branches | @'
