[user]
name = "Til Blechschmidt"
email = "me@tibl.dev"

[signing]
sign-all = true
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII/RQS4p5LRMtn8JgU0mvbMNmFfQlXIC48Qv8L03sB4A"

[ui]
default-command = "log"
paginate = "auto"
pager = "delta"

[ui.diff]
format = "git"

[template-aliases]
'format_short_signature(signature)' = 'signature.username()'
'format_timestamp(timestamp)' = 'timestamp.format("%F %H:%M")'
